// Auth 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOAD_USER = 'LOAD_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const SET_LOADING = "SET_LOADING";
export const LOGS_ERROR = "LOGS_ERROR";
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Bootcamps 
export const ALL_BOOTCAMPS = "ALL_BOOTCAMPS";
export const CURRENT_BOOTCAMP = "CURRENT_BOOTCAMP";
export const FILTERED_BOOTCAMPS = "FILTERED_BOOTCAMPS";
export const CREATE_BOOTCAMP = "CREATE_BOOTCAMP";
export const UPDATE_BOOTCAMP = "UPDATE_BOOTCAMP";
export const UPDATE_BOOTCAMP_IMG = "UPDATE_BOOTCAMP_IMG";
export const DELETE_BOOTCAMP = "DELETE_BOOTCAMP";
export const CLEAR_BOOTCAMPS = "CLEAR_BOOTCAMPS";
export const CLEAR_BOOTCAMP = "CLEAR_BOOTCAMP";
export const CLEAR_FILTERED = "CLEAR_FILTERED";
export const SET_BOOTCAMPS_LOADING = "SET_BOOTCAMPS_LOADING";
export const BOOTCAMPS_ERROR = "BOOTCAMPS_ERROR";
export const BOOTCAMPS_CLEAR_ERRORS = 'BOOTCAMPS_CLEAR_ERRORS';

// Courses 
export const ALL_COURSES = "ALL_COURSES";
export const CURRENT_COURSE = "CURRENT_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const CLEAR_COURSES = "CLEAR_COURSES";
export const CLEAR_COURSE = "CLEAR_COURSE";
export const SET_COURSES_LOADING = "SET_COURSES_LOADING";
export const COURSES_ERROR = "COURSES_ERROR";
export const COURSES_CLEAR_ERRORS = 'COURSES_CLEAR_ERRORS';

// Reviews
export const ALL_REVIEWS = "ALL_REVIEWS";
export const CURRENT_REVIEW = "CURRENT_REVIEW";
export const CREATE_REVIEW = "CREATE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const CLEAR_REVIEWS = "CLEAR_REVIEWS";
export const CLEAR_REVIEW = "CLEAR_REVIEW";
export const SET_REVIEW_LOADING = "SET_REVIEW_LOADING";
export const REVIEWS_ERROR = "REVIEWS_ERROR";
export const REVIEWS_CLEAR_ERRORS = 'REVIEWS_CLEAR_ERRORS';

// Alert 
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
